config/routes.rb
Rails.application.routes.draw do
  # resources :comics
  root to: 'comics#index'
  
  get 'latest', to: 'comics#latest'
  get 'search', to: 'comics#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
	include SeCodeChallenge

		attr_accessor 	:month,
						:num,
						:link,
						:year,
						:news,
						:safe_title,
						:transcript,
						:alt,
						:img,
						:title,
						:day

		def initialize(month, num, link, year, news, safe_title, transcript, alt, img, title, day)
			@month = response["month"]
			@num = response["num"]
			@link = response["link"]
			@year = response["year"]
			@news = response["news"]
			@safe_title = response["safe_title"]
			@transcript = response["transcript"]
			@alt = response["title"]
			@img = response["img"]
			@title = response["alt"]
			@day = response["day"]
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
require 'request'

class ComicsController < ApplicationController
  

  # GET /comics
  # GET /comics.json
  def index
  end

   # GET /comics
  # GET /comics.json
  def latest
    @comic = Request.new.get_latest_comic

    render :latest
  end

  # GET /comics/1
  # GET /comics/1.json
  def search
    @comic = Request.find(params[:num])

    render :search
  end

  # GET /comics/1
  # GET /comics/1.json
  # def show
  # end

  # GET /comics/new
  # def new
  #   @comic = Comic.new
  # end

  # GET /comics/1/edit
  # def edit
  # end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:month, :num, :link, :year, :news, :safe_title, :transcript, :alt, :img, :title, :day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_form.html.erb
<%= form_with(model: comic, local: true) do |form| %>
  <% if comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_field :month %>
  </div>

  <div class="field">
    <%= form.label :num %>
    <%= form.number_field :num %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :news %>
    <%= form.text_field :news %>
  </div>

  <div class="field">
    <%= form.label :safe_title %>
    <%= form.text_field :safe_title %>
  </div>

  <div class="field">
    <%= form.label :transcript %>
    <%= form.text_field :transcript %>
  </div>

  <div class="field">
    <%= form.label :alt %>
    <%= form.text_field :alt %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.text_field :day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Latest', latest_path %> <%= link_to 'Search', search_path %>

  

<br>

app/views/comics/new.html.erb
<h1>New Comic</h1>

<%= render 'form', comic: @comic %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @comic.month %>
</p>

<p>
  <strong>Num:</strong>
  <%= @comic.num %>
</p>

<p>
  <strong>Link:</strong>
  <%= @comic.link %>
</p>

<p>
  <strong>Year:</strong>
  <%= @comic.year %>
</p>

<p>
  <strong>News:</strong>
  <%= @comic.news %>
</p>

<p>
  <strong>Safe title:</strong>
  <%= @comic.safe_title %>
</p>

<p>
  <strong>Transcript:</strong>
  <%= @comic.transcript %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @comic.alt %>
</p>

<p>
  <strong>Img:</strong>
  <%= @comic.img %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comic.title %>
</p>

<p>
  <strong>Day:</strong>
  <%= @comic.day %>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>